authors:
  lin:
    name: 泠
    description: 改图作者
    avatar: https://q1.qlogo.cn/g?b=qq&nk=1258424041&s=100
  crt106:
    name: crt106
    description: wiki维护
    avatar: https://q1.qlogo.cn/g?b=qq&nk=814909233&s=100